eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
server:
  port: 9411
spring:
  application:
    name: zipkin-server
#spring.sleuth.sampler.percentage: 1.0
#配置RabbitMQ的配置
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest