server:
  port: 8079

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
spring:
  application:
    name: spring-cloud-zuul
zuul:
  routes:
  # 以下注释 后采用 RouteConfig.java 配置
#    api-a:
#      path: /api-a/**
#      serviceId: spring-service-ribbon
#    api-b:
#      path: /api-b/**
#      serviceId: spring-service-feign
      #url: spring-service-feign  # path  和 url 同时存在的时候 url 就是当做 serviceId 来使用
    baidu:
      url: http://www.baidu.com
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  sensitive-headers: Cookie,Set-Cookie,Authorization
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  resetclient:
    enabled: true
  okhttp:
    enabled: true
#安全验证
security:
  basic:
    enabled: true
  user:
    name: sa  # 用户名
    password: 123   # 用户密码
