eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8761/eureka/
server:
  port: 8768
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

#spring.zipkin.base-url=http://localhost:9411
#配置RabbitMQ的配置
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest